name: atravelingsaint
favicon: null
layout_spectrum: 0.24694
typography_spectrum: 0.77989
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#57544c'
    - '#251a13'
    - '#b5b6b0'
    - '#ce7577'
  brandStrength: 0.7336058563087136
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
